# Generated by Django 4.0.6 on 2022-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('publishers', models.CharField(max_length=50)),
            ],
        ),
    ]
