# Generated by Django 4.0.6 on 2022-09-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooK',
            new_name='Books',
        ),
    ]
